"""initial

Revision ID: 7bf929c72ac2
Revises: eca7fc6da6e4
Create Date: 2025-12-06 12:05:29.748478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf929c72ac2'
down_revision: Union[str, Sequence[str], None] = 'eca7fc6da6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('city_id', sa.Integer(), nullable=False))
    op.add_column('temperature', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.add_column('temperature', sa.Column('temperature', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'temperature', ['city_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'temperature', type_='unique')
    op.drop_column('temperature', 'temperature')
    op.drop_column('temperature', 'date_time')
    op.drop_column('temperature', 'city_id')
    # ### end Alembic commands ###
